/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 chicken.glb 
Author: 🇧🇷 Fog 🇧🇷 (https://sketchfab.com/fog_)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chicken-a-minecraft-movie-7e18e81118a641c6a9fd701da537ee95
Title: Chicken | A Minecraft Movie
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Chicken(props) {
  const { scene } = useGLTF('/chicken.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.655}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes._rootJoint} />
            <skinnedMesh geometry={nodes.Object_44.geometry} material={materials.Chicken} skeleton={nodes.Object_44.skeleton} />
            <skinnedMesh geometry={nodes.Object_45.geometry} material={materials.Material} skeleton={nodes.Object_45.skeleton} />
            <skinnedMesh geometry={nodes.Object_47.geometry} material={materials.Chicken} skeleton={nodes.Object_47.skeleton} />
            <skinnedMesh geometry={nodes.Object_49.geometry} material={materials.Cornea} skeleton={nodes.Object_49.skeleton} />
            <skinnedMesh geometry={nodes.Object_51.geometry} material={materials.Eyes} skeleton={nodes.Object_51.skeleton} />
            <skinnedMesh geometry={nodes.Object_53.geometry} material={materials.Chicken} skeleton={nodes.Object_53.skeleton} />
            <skinnedMesh geometry={nodes.Object_55.geometry} material={materials.Feather} skeleton={nodes.Object_55.skeleton} />
            <skinnedMesh geometry={nodes.Object_57.geometry} material={materials.Chicken} skeleton={nodes.Object_57.skeleton} />
            <skinnedMesh geometry={nodes.Object_58.geometry} material={materials.Material} skeleton={nodes.Object_58.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/chicken.glb')

export default Chicken;
